(function(){
  const maxSize=25*1024*1024,urlCache=new Map();
  function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('checklist-media',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  async function localPut(file){const handle=await db(),id=crypto.randomUUID();await new Promise((resolve,reject)=>{const tx=handle.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});handle.close();return id;}
  async function localURL(id){if(urlCache.has(id))return urlCache.get(id).url;const handle=await db();const file=await new Promise((resolve,reject)=>{const r=handle.transaction('files').objectStore('files').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});handle.close();if(!file)throw Error('Este arquivo local não está disponível neste aparelho.');const url=URL.createObjectURL(file);urlCache.set(id,{url,until:Infinity});return url;}
  async function request(client,body){const r=await client.functions.invoke('checklist-media',{body});if(r.error)throw Error('Não foi possível acessar o arquivo. Verifique a conexão e tente novamente.');if(r.data.error)throw Error(r.data.error);return r.data;}
  async function upload(file,context){if(!file.size)throw Error('O arquivo está vazio.');if(file.size>maxSize)throw Error('O limite é de 25 MB por arquivo.');if(!/^(image\/(jpeg|png|webp|gif)|audio\/(webm|ogg|mpeg|mp4|wav|x-wav)|video\/(mp4|webm|quicktime)|application\/pdf)(;.*)?$/.test(file.type))throw Error('Use imagem, áudio, vídeo ou PDF em formato compatível.');const attachment={id:crypto.randomUUID(),name:file.name||'Gravação.webm',type:file.type,size:file.size};if(context.local){attachment.localId=await localPut(file);return attachment;}if(!context.sessionId)throw Error('Aguarde o bot encaminhar seu atendimento.');const form=new FormData();form.append('file',file,attachment.name);form.append('session_id',context.sessionId);if(context.token)form.append('chat_token',context.token);const result=await request(context.client,form);return {...attachment,path:result.path};}
  async function source(attachment,context){if(attachment.localId)return localURL(attachment.localId);const cached=urlCache.get(attachment.path);if(cached&&cached.until>Date.now())return cached.url;const result=await request(context.client,{action:'sign',path:attachment.path,session_id:context.sessionId,chat_token:context.token||null});urlCache.set(attachment.path,{url:result.url,until:Date.now()+240000});return result.url;}
  async function render(host,attachment,context){if(!attachment)return;const box=document.createElement('div');box.className='attachment';box.textContent='Carregando '+attachment.name+'…';host.append(box);try{const url=await source(attachment,context);if(!host.isConnected)return;box.textContent='';let media;if(attachment.type.startsWith('image/')){media=document.createElement('img');media.alt=attachment.name;media.loading='lazy';}else if(attachment.type.startsWith('audio/')){media=document.createElement('audio');media.controls=true;media.preload='metadata';}else if(attachment.type.startsWith('video/')){media=document.createElement('video');media.controls=true;media.playsInline=true;media.preload='metadata';}else{media=document.createElement('a');media.href=url;media.target='_blank';media.rel='noopener';media.textContent=attachment.name;}if(media.tagName!=='A')media.src=url;box.append(media);const small=document.createElement('small');small.textContent=attachment.name+' · '+(attachment.size/1024/1024).toFixed(1)+' MB';box.append(small);}catch(error){box.textContent=error.message;}}
  async function recorder(onState,onFile,onError){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Gravação indisponível. Abra o aplicativo por HTTPS e permita o microfone.');const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));const rec=new MediaRecorder(stream,mime?{mimeType:mime}:{}),chunks=[];let cancelled=false,seconds=0;const timer=setInterval(()=>onState(++seconds),1000);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{clearInterval(timer);stream.getTracks().forEach(t=>t.stop());onState(null);if(!cancelled){const type=rec.mimeType||'audio/webm',ext=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm';onFile(new File(chunks,'Áudio-'+Date.now()+'.'+ext,{type}));}};rec.onerror=e=>{cancelled=true;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());onState(null);onError(e.error||Error('Não foi possível gravar.'));};rec.start();onState(0);return {stop(){if(rec.state==='recording')rec.stop();},cancel(){cancelled=true;if(rec.state==='recording')rec.stop();}};}
  window.ChecklistMedia={upload,render,recorder};
})();
