(function(){
 'use strict';
 const KEY='servis_gr_db_v6',SESSION='csr_driver_session_v2',local=new URLSearchParams(location.search).get('local')==='1';
 const config=window.CHECKLIST_CONFIG,client=!local&&window.supabase?window.supabase.createClient(config.url,config.key,{auth:{persistSession:false}}):null;
 const $=id=>document.getElementById(id),read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}');}catch{return {};}};
 const write=db=>localStorage.setItem(KEY,JSON.stringify(db)),uid=()=>crypto.randomUUID(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let driver=null,busy=false,syncing=false,installPrompt=null,recording=null,mediaFile=null,lastView='',lastNotice='',poll;
 const toast=msg=>{$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4000);};
 const state=db=>{db.driverChatStates||={};return db.driverChatStates[driver.id]||={step:'idle',data:{},activeChatId:''};};
 const saveState=(db,s)=>{db.driverChatStates[driver.id]=s;write(db);};
 const context=()=>{const s=state(read());return {local,client,sessionId:s.activeChatId,token:s.remoteToken};};
 async function rpc(name,args){if(!client)throw Error('Não foi possível conectar ao serviço. Verifique sua conexão.');const r=await client.rpc(name,args);if(r.error)throw Error(r.error.message||'Não foi possível concluir. Tente novamente.');return r.data;}
 async function password(value,salt){const bytes=new TextEncoder().encode(value),key=await crypto.subtle.importKey('raw',bytes,'PBKDF2',false,['deriveBits']);const result=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(result)).map(x=>x.toString(16).padStart(2,'0')).join('');}
 function message(db,sender,text,extra={}){const s=state(db);db.checklistChats||=[];db.checklistChats.push({id:uid(),chatId:s.activeChatId,driverId:driver.id,driverName:s.data.name||driver.name,driverPhone:driver.phone,plate:s.data.plate||'',technology:s.data.technology||'',operatorId:s.operatorId||'',sender,text,at:Date.now(),read:sender==='bot',...extra});write(db);}
 function bot(db,text){message(db,'bot',text);}
 function begin(){const db=read(),s=state(db);s.step='menu';s.data={};s.activeChatId='local-'+uid();s.operatorId='';s.remoteToken='';s.baseId='';saveState(db,s);bot(db,'Olá! Como posso te ajudar? Escolha uma das opções abaixo.');lastView='';draw();}
 function chooseService(type){const db=read(),s=state(db);s.data.serviceType=type;s.step='name';saveState(db,s);message(db,'driver',type==='monitoring'?'Monitoramento':'Checklist');bot(read(),'Perfeito! Qual é o nome completo do condutor?');lastView='';draw();}
 function chooseOperator(db){const candidates=(db.users||[]).filter(u=>u.active!==false&&['Operador','Lider','Supervisor','Coordenador','Gerente','Administrador'].includes(u.funcao||u.cargo)&&(u.perms?.checklist_chat??db.rolePermissionDefaults?.[u.funcao||u.cargo]?.checklist_chat??true)&&(u.perms?.chatChecklist??db.rolePermissionDefaults?.[u.funcao||u.cargo]?.chatChecklist??true));const load=id=>new Set((db.checklistChats||[]).filter(m=>m.operatorId===id&&!m.closed).map(m=>m.chatId)).size;return candidates.sort((a,b)=>load(a.id)-load(b.id))[0];}
 function chooseMonitoringOperator(db,plate){const clean=(plate||'').toUpperCase().replace(/[-\s]/g,'');const driverRow=(db.mockFleetDrivers||[]).find(d=>d.plate===clean);if(!driverRow)return {notice:'Veículo não localizado na base de dados. Um coordenador vai encaminhar manualmente.'};const link=(db.baseCarriers||[]).find(b=>b.carrierId===driverRow.carrierId);if(!link)return {notice:'Transportadora localizada, mas sem base vinculada. Um coordenador vai encaminhar manualmente.'};const ids=(db.baseOperators||[]).filter(bo=>bo.baseId===link.baseId).map(bo=>bo.userId);const candidates=ids.map(id=>(db.users||[]).find(u=>u.id===id)).filter(u=>u&&u.active!==false&&(u.perms?.monitoring_chat??db.rolePermissionDefaults?.[u.funcao||u.cargo]?.monitoring_chat??false));if(!candidates.length)return {baseId:link.baseId,notice:'Base localizada, mas sem operador de monitoramento disponível no momento.'};const load=id=>new Set((db.checklistChats||[]).filter(m=>m.operatorId===id&&!m.closed).map(m=>m.chatId)).size;const min=Math.min(...candidates.map(c=>load(c.id)));const tied=candidates.filter(c=>load(c.id)===min);return {operatorId:tied[Math.floor(Math.random()*tied.length)].id,baseId:link.baseId};}
 async function route(){let db=read(),s=state(db);const type=s.data.serviceType;try{let notice='';if(local){if(type==='checklist'){const op=chooseOperator(db);if(!op)throw Error('Nenhum operador disponível. Tente novamente em instantes.');s.operatorId=op.id;}else{const r=chooseMonitoringOperator(db,s.data.plate);s.operatorId=r.operatorId||'';s.baseId=r.baseId||'';notice=r.notice||'';}}else{const rpcName=type==='monitoring'?'start_driver_monitoring_chat':'start_driver_checklist_chat';const [r]=await rpc(rpcName,{driver_account:driver.id,account_token:driver.remoteToken,vehicle_plate:s.data.plate,tracker_technology:s.data.technology,reported_name:s.data.name});const previous=s.activeChatId;s.activeChatId=r.session_id;s.remoteToken=r.driver_token;s.operatorId=r.operator_id||'';(db.checklistChats||[]).filter(m=>m.chatId===previous&&m.driverId===driver.id).forEach(m=>m.chatId=s.activeChatId);if(type==='monitoring'&&!r.operator_id)notice=r.notice||'Aguardando encaminhamento manual.';}
 s.step='operator';saveState(db,s);const text='Solicitação de '+(type==='monitoring'?'monitoramento':'checklist')+'\nCondutor: '+s.data.name+'\nPlaca: '+s.data.plate+'\nTecnologia: '+s.data.technology;
 if(local)message(db,'driver',text,{request:true});else await rpc('send_checklist_driver_message',{chat_session:s.activeChatId,chat_token:s.remoteToken,message_body:text});
 db=read();bot(db,s.operatorId?'Seus dados foram enviados. Aguarde o operador continuar o atendimento.':notice||'Seus dados foram enviados. Aguarde o encaminhamento.');await sync();
 }catch(e){s.step='waiting';saveState(db,s);toast(e.message);}draw();}
 async function send(){if(busy||!driver)return;const input=$('message'),text=input.value.trim();if(!text)return;const db=read(),s=state(db);if(s.step==='closed'||s.step==='waiting'||s.step==='menu')return;busy=true;input.disabled=true;try{if(s.step==='operator'){if(local)message(db,'driver',text);else await rpc('send_checklist_driver_message',{chat_session:s.activeChatId,chat_token:s.remoteToken,message_body:text});}else{if(s.step==='name'&&text.length<3)throw Error('Informe o nome completo.');if(s.step==='plate'&&!/^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$/.test(text.toUpperCase().replace(/[-\s]/g,'')))throw Error('Informe uma placa válida, como ABC1D23.');message(db,'driver',text);if(s.step==='name'){s.data.name=text;s.step='plate';saveState(db,s);bot(db,'Qual é a placa do veículo?');}else if(s.step==='plate'){s.data.plate=text.toUpperCase().replace(/[-\s]/g,'');s.step='technology';saveState(db,s);bot(db,'Informe a tecnologia do rastreador.');}else if(s.step==='technology'){s.data.technology=text;saveState(db,s);await route();}}
 input.value='';await sync();draw();}catch(e){toast(e.message);}finally{busy=false;input.disabled=false;updateComposer();}}
 function draw(){if(!driver)return;const db=read(),s=state(db),all=(db.checklistChats||[]).filter(m=>m.driverId===driver.id&&m.chatId===s.activeChatId).sort((a,b)=>a.at-b.at);const list=s.step==='closed'?all.filter(m=>m.sender==='bot'&&m.closed||m.sender==='bot'&&m.text.startsWith('Checklist CHK-')):all;const signature=JSON.stringify(list)+s.step;if(signature!==lastView){lastView=signature;const box=$('messages'),near=box.scrollHeight-box.scrollTop-box.clientHeight<100;box.innerHTML='<div class="day">'+(s.step==='closed'?'ATENDIMENTO CONCLUÍDO':'ATENDIMENTO CHECKLIST')+'</div>'+list.map(m=>'<article class="bubble '+(m.sender==='driver'?'mine':m.sender==='bot'?'bot':'')+'" data-message="'+esc(m.id)+'">'+(m.sender==='bot'?'<b class="bot-label">Assistente Checklist</b>':'')+'<p>'+esc(m.text)+'</p><span>'+new Date(m.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'</span></article>').join('');list.forEach(m=>{if(m.attachment){const host=Array.from(box.querySelectorAll('[data-message]')).find(x=>x.dataset.message===m.id);ChecklistMedia.render(host,m.attachment,context());}});if(near||s.step!=='operator')box.scrollTop=box.scrollHeight;const last=list.at(-1);if(last&&last.sender!=='driver'&&last.id!==lastNotice){if(lastNotice&&driver.notifications!==false&&document.visibilityState==='hidden'&&window.Notification?.permission==='granted')navigator.serviceWorker?.ready.then(r=>r.showNotification('Checklist',{body:last.sender==='bot'?'Seu atendimento foi atualizado.':'Você recebeu uma mensagem.',icon:'icons/icon-192.png',tag:'checklist-message'}));lastNotice=last.id;}}
 $('chat-status-text').textContent={menu:'Escolha uma opção',name:'Assistente · identificação',plate:'Assistente · veículo',technology:'Assistente · rastreador',operator:'Atendimento com a central',waiting:'Aguardando encaminhamento',closed:'Atendimento concluído'}[s.step]||'Assistente Smart Chat';updateComposer();}
 function updateComposer(){if(!driver)return;const s=state(read());$('message-form').hidden=['closed','waiting','menu'].includes(s.step);$('quick-replies').hidden=s.step!=='menu';$('new-service').hidden=s.step!=='closed';$('retry-service').hidden=s.step!=='waiting';$('attach').disabled=s.step!=='operator'||busy;$('record').disabled=s.step!=='operator'||busy;const text=!!$('message').value.trim();$('send-message').hidden=!text;$('record').hidden=text;}
 function records(){if(!driver)return;const rows=(read().driverChecklistRecords||[]).filter(r=>r.driverId===driver.id).sort((a,b)=>b.finishedAt-a.finishedAt);$('record-list').innerHTML=rows.map(r=>'<article class="record-card"><header><div><h3>'+esc(r.number)+'</h3><time>'+new Date(r.finishedAt).toLocaleString('pt-BR')+'</time></div><span class="record-status '+esc(r.status.toLowerCase())+'">'+esc(r.status)+'</span></header>'+(r.status!=='Aprovado'&&r.reason?'<p><b>Motivo:</b> '+esc(r.reason)+'</p>':'')+'</article>').join('')||'<div class="empty-records">Os números dos seus checklists aparecerão aqui após a conclusão do atendimento.</div>';}
 async function sync(){if(!driver||local||syncing)return;syncing=true;const account=driver;try{let db=read(),s=state(db);const rows=await rpc('list_driver_service_records',{driver_account:account.id,account_token:account.remoteToken});if(driver!==account)return;db=read();db.driverChecklistRecords=(db.driverChecklistRecords||[]).filter(r=>r.driverId!==account.id).concat((rows||[]).map(r=>({id:r.checklist_number,number:r.checklist_number,driverId:account.id,status:r.status,reason:r.reason,finishedAt:new Date(r.finished_at).getTime()})));write(db);
 if(s.remoteToken){const msgs=await rpc('read_checklist_driver_messages',{chat_session:s.activeChatId,chat_token:s.remoteToken});if(driver!==account)return;db=read();s=state(db);db.checklistChats=(db.checklistChats||[]).filter(m=>m.remoteSession!==s.activeChatId).concat((msgs||[]).map(m=>({id:m.id,chatId:s.activeChatId,remoteSession:s.activeChatId,driverId:account.id,operatorId:s.operatorId,sender:m.sender_type,text:m.body,attachment:m.attachment,at:new Date(m.created_at).getTime()})));if(msgs.some(m=>m.sender_type==='bot'&&/^(Checklist CHK-|Atendimento MON-)/.test(m.body))){s.step='closed';saveState(db,s);}else write(db);}
 draw();records();}catch(e){$('chat-status-text').textContent='Sem atualização · verifique a conexão';}finally{syncing=false;}}
 function page(name){document.querySelectorAll('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===name));document.querySelectorAll('[data-nav]').forEach(e=>e.classList.toggle('active',e.dataset.nav===name));$('screen-title').textContent={chat:'Checklist',records:'Registros',settings:'Configurações'}[name];if(name==='records')records();if(name==='chat')draw();}
 async function openApp(){
 if(!local){try{const rows=await rpc('resume_driver_chat',{driver_account:driver.id,account_token:driver.remoteToken});if(rows?.length){const r=rows[0],db=read();saveState(db,{step:'operator',activeChatId:r.session_id,remoteToken:r.driver_token,operatorId:r.operator_id,data:{name:r.driver_name,plate:r.vehicle_plate,technology:r.technology,serviceType:r.service_type}});}}catch(e){toast('Não foi possível recuperar o atendimento: '+e.message);}}
  $('auth-screen').hidden=true;$('app-screen').hidden=false;$('driver-avatar').textContent=driver.name[0];$('settings-avatar').textContent=driver.name[0];$('settings-name').textContent=driver.name;$('settings-phone').textContent=driver.phone;$('notifications-toggle').checked=driver.notifications!==false;page('chat');const s=state(read());if(s.step==='idle')begin();await sync();clearInterval(poll);poll=setInterval(()=>{draw();records();sync();},3500);}
 async function auth(form,register){if(busy)return;busy=true;const button=form.querySelector('[type=submit]');button.disabled=true;const v=Object.fromEntries(new FormData(form)),login=v.login.trim().toLowerCase(),phone=(v.phone||'').replace(/\D/g,'');try{let account;if(local){const db=read();db.driverAccounts||=[];if(register){if(phone.length<10||phone.length>13)throw Error('Informe o telefone com DDD.');if(db.driverAccounts.some(a=>a.phone===phone||a.login===login))throw Error('Telefone ou login já cadastrado.');const salt=uid();account={id:'driver-'+uid(),name:v.name.trim(),phone,login,salt,passwordHash:await password(v.password,salt),notifications:true};db.driverAccounts.push(account);write(db);}else{account=db.driverAccounts.find(a=>a.login===login);if(!account?.salt||account.passwordHash!==await password(v.password,account.salt))throw Error('Login ou senha inválidos.');}}else{const rows=register?await rpc('register_checklist_driver',{driver_name:v.name.trim(),driver_phone:phone,driver_login:login,driver_password:v.password}):await rpc('login_checklist_driver',{driver_login:login,driver_password:v.password});if(!rows?.length)throw Error('Login ou senha inválidos.');const r=rows[0];account={id:r.driver_id,name:r.full_name,phone:r.phone,login,remoteToken:r.session_token,notifications:r.notifications!==false};}
 driver=account;localStorage.setItem(SESSION,JSON.stringify(account));form.reset();await openApp();}catch(e){toast(e.message);}finally{busy=false;button.disabled=false;}}
 $('login-form').onsubmit=e=>{e.preventDefault();auth(e.currentTarget,false);};$('register-form').onsubmit=e=>{e.preventDefault();auth(e.currentTarget,true);};
 document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('login-form').hidden=b.dataset.authTab!=='login';$('register-form').hidden=b.dataset.authTab!=='register';});
 document.querySelectorAll('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector('input');i.type=i.type==='password'?'text':'password';b.setAttribute('aria-label',i.type==='text'?'Ocultar senha':'Mostrar senha');});
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>page(b.dataset.nav));$('message-form').onsubmit=e=>{e.preventDefault();send();};$('message').oninput=updateComposer;$('new-service').onclick=begin;$('retry-service').onclick=route;
 document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>chooseService(b.dataset.service));
 $('attach').onclick=()=>$('attachment-sheet').showModal();$('attachment-close').onclick=()=>$('attachment-sheet').close();document.querySelectorAll('[data-file-type]').forEach(b=>b.onclick=()=>{$('file-input').accept=b.dataset.fileType;$('file-input').click();$('attachment-sheet').close();});
 function preview(file){mediaFile=file;$('media-preview-name').textContent=file.name+' · '+(file.size/1024/1024).toFixed(1)+' MB';$('media-preview').showModal();}
 $('file-input').onchange=e=>{if(e.target.files[0])preview(e.target.files[0]);e.target.value='';};$('media-cancel').onclick=()=>{mediaFile=null;$('media-preview').close();};
 $('media-send').onclick=async()=>{if(!mediaFile||busy)return;busy=true;$('media-send').disabled=true;try{const attachment=await ChecklistMedia.upload(mediaFile,context()),db=read(),s=state(db);if(s.step!=='operator')throw Error('Este atendimento foi encerrado. Inicie outro atendimento.');if(local)message(db,'driver','',{attachment});else await rpc('send_checklist_driver_attachment',{chat_session:s.activeChatId,chat_token:s.remoteToken,file_attachment:attachment});mediaFile=null;$('media-preview').close();await sync();draw();}catch(e){toast(e.message);}finally{busy=false;$('media-send').disabled=false;}};
 $('record').onclick=async()=>{if(recording)return;try{recording=await ChecklistMedia.recorder(seconds=>{$('recording-strip').hidden=seconds===null;if(seconds===null)recording=null;if(seconds!==null)$('recording-time').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');if(seconds>=180)recording?.stop();},preview,e=>toast(e.message));}catch(e){toast(e.name==='NotAllowedError'?'Permita o microfone no navegador para gravar áudio.':e.message);}};$('record-stop').onclick=()=>recording?.stop();$('record-cancel').onclick=()=>recording?.cancel();
 $('notifications-toggle').onchange=async function(){try{if(this.checked&&window.Notification){const permission=await Notification.requestPermission();if(permission!=='granted'){this.checked=false;throw Error('Permita notificações nas configurações do navegador.');}}driver.notifications=this.checked;if(!local)await rpc('set_checklist_driver_notifications',{driver_account:driver.id,account_token:driver.remoteToken,enabled:this.checked});localStorage.setItem(SESSION,JSON.stringify(driver));}catch(e){toast(e.message);}};
 $('logout').onclick=()=>{recording?.cancel();clearInterval(poll);driver=null;lastView='';localStorage.removeItem(SESSION);$('app-screen').hidden=true;$('auth-screen').hidden=false;};
 async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null;}else toast('Android: menu → Instalar aplicativo. iPhone: Compartilhar → Adicionar à Tela de Início.');} $('install-auth').onclick=install;$('install-settings').onclick=install;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install-auth').hidden=false;});
 window.addEventListener('storage',e=>{if(e.key===KEY&&driver){draw();records();}});window.addEventListener('pagehide',()=>recording?.cancel());
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
 try{const cached=JSON.parse(localStorage.getItem(SESSION)||'null');if(cached&&typeof cached==='object'&&(local||cached.remoteToken)){driver=cached;openApp();}}catch{}
})();
